
version: "3.8"
services:
  gameapptestauso123:
    image: penbeaa/gameappnewimage:latest
    build: .
    container_name: gameappautotest123
    ports:
      - "5000:3000"
    environment:
       - PORT=5000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
