
version: "3.8"
services:
  gameapptestauso123:
    image: amalan06/gameappnewimage:latest
    build: .
    container_name: gameappautotest123
    ports:
      - "80:3000"
    environment:
       - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
